### ISSUE TITLE
NULL values creating a java.lang.NullPointerException in SOLR

### ISSUE THREAD

**Issue by tobias-redmann** [jeroenherczeg/laravel-scout-solr#1]
## Detailed description

When the models have properties with NULL values, the solr update fails. For example:
`(
  'id' => 17,
  'gender' => NULL,
  'type' => 'person',
  'first_name' => 'Tobias',
  'last_name' => 'Redmann',
  'company' => NULL,
  'created_at' => '2018-10-09 16:53:19',
  'updated_at' => '2018-10-09 16:53:19',
) `

## Context

We need somehow to make sure, that the update not fails. probably checking the document/model array before for null value and remove them ($model->toSearchableArray()). Otherwise the developer needs to make sure, that the models are without null values.

## Your environment

- Scout 5.*
- Laravel 5.7.*
- Solr in Docker 7.4*

**Comment by FrittenKeeZ** [comment]
I've fixed this with #5
